### ISSUE TITLE
Issue when trying to install ggiraphExtra

### ISSUE THREAD

**Issue by fuyu00** [LCBC-UiO/tsdrtools#2]
Using R/3.6

When trying to use tsd_package_install for the package ggiraphExtra I get a "success" message for every package but then R says "there is no package called 'ggiraphExtra'"

here is a screenshot of the terminal:
![image](https://user-images.githubusercontent.com/45471612/91586957-68077580-e956-11ea-80c3-69ae1dda9581.png)

**Comment by drmowinckels** [comment]
Hi! Thanks for the issue. I also just discovered this happening with another package I was installing. Catching the failed install along the way is a little tricker than expected. I hope to be able to figure out how to better catch the errors.

**Comment by fuyu00** [comment]
I'm also getting the same issue installing "ggstatsplot" - if there's any extra info I can provide to isolate the issue let me know :)

**Comment by drmowinckels** [comment]
Hi!

Ok, had the time to work a little more on things, but have not had time to test inside TSD yet.

[Grab a new source file](https://github.com/LCBC-UiO/tsdrtools/raw/master/source/tsdrtools_0.1.03.tar.gz) for the package to install in TSD, and try again. This time, save the output of the install function to an object, and then you will be able to inspect any error logs for failing package. Which should provide some information on why they are failing, and what we might be able to do to make it work. 

Some extra information on that in the [package site](https://lcbc-uio.github.io/tsdrtools/articles/tsdrtools.html)

**Comment by fuyu00** [comment]
Ok, 
I got the error info now

![image](https://user-images.githubusercontent.com/45471612/91978237-154a0700-ed24-11ea-9d98-d14ee9c1cae8.png)

By the way, the instruction of the github page to get the error log might be wrong - I could only get the log via 

`status <- tsd_package_install("dplyr.zip")` rather than `status <- tsd_package_prepare("dplyr.zip")`

**Comment by IndrajeetPatil** [comment]
> Ok,
> I got the error info now
> 
> ![image](https://user-images.githubusercontent.com/45471612/91978237-154a0700-ed24-11ea-9d98-d14ee9c1cae8.png)
> 
> By the way, the instruction of the github page to get the error log might be wrong - I could only get the log via
> 
> `status <- tsd_package_install("dplyr.zip")` rather than `status <- tsd_package_prepare("dplyr.zip")`

Hmm, the error here is rather clear: the installation can't find the needed dependencies of `ggstatsplot`, viz. `pairwiseComparisons`, `statsExpressions`, and `groupedstats`. Once you install them, you shouldn't have any installation issue. IF they persist, fee free to raise issue here: https://github.com/IndrajeetPatil/ggstatsplot/issues

**Comment by drmowinckels** [comment]
THanks for the feedback on the code  on the webpage. You'd think I would be able to keep two functions apart having made them.

The errors above, atleast two of them I know the answer to. 

Both errors regarding "failed to lock directory" can happen when a previous install is aborted mid-install. This lock directories are necessary for temporary install, and if they already exist this error can happen. Manually delete both these lock directories using `rm -r`. 

The other error may happen because of me not having set the install sequence correctly (ie. lme4 install maybe is coming before groupedstats). This will fail the install. I will look into that.

**Comment by drmowinckels** [comment]
Hi!

After looking a little, it seems like ggstatsplot has a backwards dependency on Rrmpfr, which requires an OS library that is not by default installed on TSD `mpfr-devel` 
https://rmpfr.r-forge.r-project.org/

You will need to ask IT to install this on your machine and submit host.

After this, I believe you should be able to install ggstatsplot from within TSD even without this package.

**Comment by drmowinckels** [comment]
When it comes to ggiraphExtra, this can be easily installed if you load the correct R module in the terminal.
The foss R modules have extra OS libraries installed, and correctly set gcc so most packages install without alot of issues.
This did unfortunately not work for the  ggstatsplot package, for for ggiraphExtra, this worked for me on TSD:

```
module load R/4.0.0-foss-2020a
Rscript --verbose -e 'install.packages("ggiraphExtra")'
```

**Comment by IndrajeetPatil** [comment]
> Hi!
> 
> After looking a little, it seems like ggstatsplot has a backwards dependency on Rrmpfr, which requires an OS library that is not by default installed on TSD `mpfr-devel`
> https://rmpfr.r-forge.r-project.org/
> 
> You will need to ask IT to install this on your machine and submit host.
> 
> After this, I believe you should be able to install ggstatsplot from within TSD even without this package.

Thanks for tracking the source of this down!

Indeed, I need to specify this when I build `ggstatsplot` on Travis:
https://github.com/IndrajeetPatil/ggstatsplot/blob/e04911ee07329e650b08ee6bd28a40a2c2ea0bec/.travis.yml#L11-L16

I will add a note about this in `README` installation instructions.
