### ISSUE TITLE
Failed to load the Qt platform plugin "xcb" when trying to run rstudio.

### ISSUE THREAD

**Issue by johanrd** [LCBC-UiO/tsdrtools#4]
Hi.

I've followed [this guide](https://rdrr.io/github/LCBC-UiO/tsdrtools/f/vignettes/rstudio-tsd-install.Rmd) to install rstudio on tsd.

All steps seem to be successful, however I get the following error message when trying to run `rstudio`:

```console 
-bash-4.2$ rstudio
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb

Aborted
```

Google seems to respond with a lot of similar cases. Both a [qt generic issue](https://forum.qt.io/topic/111553/solved-qt-qpa-plugin-could-not-find-the-qt-platform-plugin-xcb-in/6) and an [Rstudio specific issue](https://github.com/rstudio/rstudio/issues/4694) seems to point the suspicion to a missing `QT_PLUGIN_PATH` path. I've checked `/usr/lib/qt/plugins` and there there seems to be no `/usr/lib/qt` folder.

Are there other locations for any qt plugins that may be installed? Or any way to install them? (I guess `apt-get install libqt5gui5` as proposed [here](https://community.rstudio.com/t/rstudio-wont-launch-error-message-about-qt-qpa-plugin/38124/2) is not very tsd friendly).

For reference, I tried with both the latest [rstudio 1.4.1103](https://rstudio.com/products/rstudio/download/#download) and with [1.3.1093](https://rstudio.com/products/rstudio/older-versions/). 

```console
hostnamectl:

 Static hostname: pXXX-submit.tsd.uio.no
     CPE OS Name: cpe:/o:redhat:entreprise_linux:7.9:GA:server
```

Thanks,

**Comment by drmowinckels** [comment]
Hi.

To install the newest RStudio on TSD your Linux Vms must run RHEL7 or above. The standard VMs on TSD run RHEL6 and you will not be able to open RStudio. Are you sure you are switched to the Rhel6 VM?

Secondly, I have recently has TSD install RStudio directly on our VMs for us, rather than trying to maintain them our selves. This has so far been a huge relief, and I encourage you to contact you project admin and IT and ask them to install the latest RStudio on all your projects VMs

**Comment by johanrd** [comment]
Hi. Thanks for your reply.

According to `hostnamectl` (see above), my VM actually seems to run `Red Hat Entreprise Linux Server release  7.9 (Maipo)`.

Anyways, it seems like a good idea to contact TSD to see if they can install the latest RStudio for me. I'll do that. 

Thanks.

**Comment by drmowinckels** [comment]
Your host also indicates that you are on a submit node, where I think GUI stuff is not so easily accessible. 
The procedure described is intended for the login nodes. So that might also be a core issue.
