### ISSUE TITLE
Installation of tsdrtools inside ted

### ISSUE THREAD

**Issue by RubenARC** [LCBC-UiO/tsdrtools#5]
Hi. 
I tried to install tsdrtools inside tsp and I have the error message attached. Please see also the information of my session. Thanks. 
![installation_method](https://user-images.githubusercontent.com/79651594/119546248-0153a300-bd94-11eb-9888-68af3d92dfd3.png)

the error that I get is 

Installing package into 'C:/Users/myidintsd/Documents/R/win-library/4.0' (as 'lib' is unspecified)

![error_](https://user-images.githubusercontent.com/79651594/119546763-922a7e80-bd94-11eb-9faa-7343f7d01725.png)

Thank you very much for your help.

**Comment by drmowinckels** [comment]
Hi!

Installing the {tsdrtools} package within TSD requires a different way of doing things. tsdrtools is not on CRAN, and as such it also does not exist in the mini-CRAN copied into TSD (which you are connecting to in your example). 

In the README of this repository you find some information on what you need to do to install it on TSD. I have not tried this on windows, but it should work there too. 


for installation of this package inside TSD, download the newest source
file from <https://github.com/LCBC-UiO/tsdrtools/>.

Transfer the package to TSD (import it), and install as a source
package.

``` r
install.packages("/path/to/tsdrtools.tar.gz", repo = NULL)
```
