### ISSUE TITLE
Rstudio graphics disappearing

### ISSUE THREAD

**Issue by K-Aurora** [LCBC-UiO/tsdrtools#6]
I have a problem with setting up my own rstudio in tsd. I used the following steps (based on https://lcbc-uio.github.io/tsdrtools/articles/rstudio-tsd-install.html):

- Make a folder for common tools for your project, with a subfolder for rstudio
 mkdir -p /cluster/projects/pXXXX/tools/rstudio_{user}

- Move the rstudio tar
 mv/tsd/p1068/data/durable/file-import/p1068-member-group/{rstudio-2021.09.0-351-x86_64-fedora.tar.gz} /cluster/projects/pXXXX/tools/rstudio_{user}

- Go to the folder
 cd /cluster/projects/pXXXX/tools/rstudio_{user}

- Extract the tar-ball
 tar xvzf { rstudio-2021.09.0-351-x86_64-fedora.tar.gz}

- Set the new Rstudio to be the current one with a symbolic link
 ln -s {rstudio-2021.09.0+351} current

- Make an alias in .bashrc
 alias rstudio=/cluster/projects/pXXX/tools/rstudio_{user}/current/bin/rstudio

 - Once this is done load module with bioconductor:
 module load R-bundle-Bioconductor/3.9-foss-2019a-R-3.6.0

 - run rstudio in terminal:
 rstudio

rstudio is open and functioning, but the graphical interface seems to be partly disappearing. It is ok to use the first minutes, but after a while almost everything disappears (se attached picture).

Any idea why this may happen, and how to fix it?

<img width="454" alt="Bilde1" src="https://user-images.githubusercontent.com/51743783/137911711-e2c76f85-dda6-4c59-8969-6c385ea4325c.png">

**Comment by drmowinckels** [comment]
Hi!

Lately, we've been asking IT to install RStudio on our projects. This has by far been more successful than administering RStudio our selves. I suggest sending off a ticket to tsd-drift and ask for RStudio to be installed on your login VMs. This is usually a first-line request solved within a day or two.
